-- MySQL Script generated by MySQL Workbench
-- 07/28/15 21:12:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema EDEIP
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `UTILISATEUR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UTILISATEUR` (
  `idUtilisateur` INT NOT NULL AUTO_INCREMENT,
  `nomUtilisateur` VARCHAR(255) NOT NULL,
  `prenomUtilisateur` VARCHAR(255) NOT NULL,
  `adr1Utilisateur` VARCHAR(255) NULL,
  `adr2Utilisateur` VARCHAR(255) NULL,
  `cpUtilisateur` VARCHAR(5) NULL,
  `villeUtilisateur` VARCHAR(255) NULL,
  `actifUtilisateur` TINYINT(1) NULL DEFAULT 1,
  `mailUtilisateur` VARCHAR(255) NULL,
  `dateNaissanceUtilisateur` VARCHAR(255) NULL,
  `dateInscriptionUtilisateur` VARCHAR(255) NULL,
  PRIMARY KEY (`idUtilisateur`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nomPrenomUtilisateur_UNIQUE` ON `UTILISATEUR` (`nomUtilisateur` ASC, `prenomUtilisateur` ASC);


-- -----------------------------------------------------
-- Table `CONNEXION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CONNEXION` (
  `idUtilisateur` INT NOT NULL,
  `loginUtilisateur` VARCHAR(255) NOT NULL,
  `mdpUtilisateur` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idUtilisateur`),
  CONSTRAINT `fkConnexionUtilisateur`
    FOREIGN KEY (`idUtilisateur`)
    REFERENCES `UTILISATEUR` (`idUtilisateur`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `loginUtilisateur_UNIQUE` ON `CONNEXION` (`loginUtilisateur` ASC);

CREATE INDEX `loginUtilisateur_INDEX` ON `CONNEXION` (`loginUtilisateur` ASC);


-- -----------------------------------------------------
-- Table `ADMINISTRATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ADMINISTRATION` (
  `idAdministration` INT NOT NULL,
  PRIMARY KEY (`idAdministration`),
  CONSTRAINT `fkAdministrationUtilisateur`
    FOREIGN KEY (`idAdministration`)
    REFERENCES `UTILISATEUR` (`idUtilisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RESPONSABLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RESPONSABLE` (
  `idResponsable` INT NOT NULL,
  PRIMARY KEY (`idResponsable`),
  CONSTRAINT `idResponsableUtilisateur`
    FOREIGN KEY (`idResponsable`)
    REFERENCES `UTILISATEUR` (`idUtilisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PROFESSEUR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROFESSEUR` (
  `idProfesseur` INT NOT NULL,
  PRIMARY KEY (`idProfesseur`),
  CONSTRAINT `fkProfesseurUtilisateur`
    FOREIGN KEY (`idProfesseur`)
    REFERENCES `UTILISATEUR` (`idUtilisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MODULE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MODULE` (
  `idModule` INT NOT NULL AUTO_INCREMENT,
  `libelleModule` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idModule`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NIVEAU`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NIVEAU` (
  `idNiveau` INT NOT NULL AUTO_INCREMENT,
  `libelleNiveau` VARCHAR(255) NOT NULL,
  `idModule` INT NOT NULL,
  PRIMARY KEY (`idNiveau`),
  CONSTRAINT `fkNiveauModule`
    FOREIGN KEY (`idModule`)
    REFERENCES `MODULE` (`idModule`))
ENGINE = InnoDB;

CREATE INDEX `fkNiveauModule_idx` ON `NIVEAU` (`idModule` ASC);


-- -----------------------------------------------------
-- Table `ELEVE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ELEVE` (
  `idEleve` INT NOT NULL,
  `idNiveau` INT NULL,
  PRIMARY KEY (`idEleve`),
  CONSTRAINT `fkEleveUtilisateur`
    FOREIGN KEY (`idEleve`)
    REFERENCES `UTILISATEUR` (`idUtilisateur`),
  CONSTRAINT `fkEleveNiveau`
    FOREIGN KEY (`idNiveau`)
    REFERENCES `NIVEAU` (`idNiveau`))
ENGINE = InnoDB;

CREATE INDEX `fkEleveNiveau_idx` ON `ELEVE` (`idNiveau` ASC);


-- -----------------------------------------------------
-- Table `ELEVE_RESPONSABLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ELEVE_RESPONSABLE` (
  `idEleve` INT NOT NULL,
  `idResponsable` INT NOT NULL,
  PRIMARY KEY (`idEleve`, `idResponsable`),
  CONSTRAINT `fkEleveResponsableEleve`
    FOREIGN KEY (`idEleve`)
    REFERENCES `ELEVE` (`idEleve`),
  CONSTRAINT `fkEleveResponsableResponsable`
    FOREIGN KEY (`idResponsable`)
    REFERENCES `RESPONSABLE` (`idResponsable`))
ENGINE = InnoDB;

CREATE INDEX `fkEleveResponsableResponsable_idx` ON `ELEVE_RESPONSABLE` (`idResponsable` ASC);


-- -----------------------------------------------------
-- Table `MATIERE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MATIERE` (
  `idMatiere` INT NOT NULL AUTO_INCREMENT,
  `libelleMatiere` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idMatiere`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MATIERE_NIVEAU`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MATIERE_NIVEAU` (
  `idMatiereNiveau` INT NOT NULL AUTO_INCREMENT,
  `idMatiere` INT NOT NULL,
  `idNiveau` INT NOT NULL,
  PRIMARY KEY (`idMatiereNiveau`),
  CONSTRAINT `fkMatiereNiveauMatiere`
    FOREIGN KEY (`idMatiere`)
    REFERENCES `MATIERE` (`idMatiere`),
  CONSTRAINT `fkMatiereNiveauNiveau`
    FOREIGN KEY (`idNiveau`)
    REFERENCES `NIVEAU` (`idNiveau`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `UNIQUE_MatiereNiveau` ON `MATIERE_NIVEAU` (`idMatiere` ASC, `idNiveau` ASC);

CREATE INDEX `fkMatiereNiveauNiveau_idx` ON `MATIERE_NIVEAU` (`idNiveau` ASC);


-- -----------------------------------------------------
-- Table `ELEVE_MATIERE_NIVEAU`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ELEVE_MATIERE_NIVEAU` (
  `idEleve` INT NOT NULL,
  `idMatiereNiveau` INT NOT NULL,
  PRIMARY KEY (`idEleve`, `idMatiereNiveau`),
  CONSTRAINT `fkEleveMatiereNiveauEleve`
    FOREIGN KEY (`idEleve`)
    REFERENCES `ELEVE` (`idEleve`),
  CONSTRAINT `fkEleveMatiereNiveauMatiereNiveau`
    FOREIGN KEY (`idMatiereNiveau`)
    REFERENCES `MATIERE_NIVEAU` (`idMatiereNiveau`))
ENGINE = InnoDB;

CREATE INDEX `fkEleveMatiereNiveauMatiereNiveau_idx` ON `ELEVE_MATIERE_NIVEAU` (`idMatiereNiveau` ASC);


-- -----------------------------------------------------
-- Table `DOMAINE_CPT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DOMAINE_CPT` (
  `idDomaineCpt` INT NOT NULL AUTO_INCREMENT,
  `libelleDomaineCpt` VARCHAR(255) NOT NULL,
  `idMatiereNiveau` INT NOT NULL,
  PRIMARY KEY (`idDomaineCpt`),
  CONSTRAINT `fkDomaineCptMaterielNiveau`
    FOREIGN KEY (`idMatiereNiveau`)
    REFERENCES `MATIERE_NIVEAU` (`idMatiereNiveau`))
ENGINE = InnoDB;

CREATE INDEX `fkDomaineCptMaterielNiveau_idx` ON `DOMAINE_CPT` (`idMatiereNiveau` ASC);


-- -----------------------------------------------------
-- Table `POINT_CPT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POINT_CPT` (
  `idPointCpt` INT NOT NULL AUTO_INCREMENT,
  `libellePoitnCpt` VARCHAR(255) NOT NULL,
  `idDomaineCpt` INT NOT NULL,
  PRIMARY KEY (`idPointCpt`),
  CONSTRAINT `fkPointCptDomaineCpt`
    FOREIGN KEY (`idDomaineCpt`)
    REFERENCES `DOMAINE_CPT` (`idDomaineCpt`))
ENGINE = InnoDB;

CREATE INDEX `fkPointCptDomaineCpt_idx` ON `POINT_CPT` (`idDomaineCpt` ASC);


-- -----------------------------------------------------
-- Table `NIVEAU_CPT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NIVEAU_CPT` (
  `idNiveauCpt` INT NOT NULL AUTO_INCREMENT,
  `libelleNiveauCpt` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idNiveauCpt`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `POINT_CPT_ELEVE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POINT_CPT_ELEVE` (
  `idPointCpt` INT NOT NULL,
  `idEleve` INT NOT NULL,
  `idNiveauCpt` INT NOT NULL,
  PRIMARY KEY (`idPointCpt`, `idEleve`),
  CONSTRAINT `fkPointCptEleveEleve`
    FOREIGN KEY (`idEleve`)
    REFERENCES `ELEVE` (`idEleve`),
  CONSTRAINT `fkPointCptElevePointCpt`
    FOREIGN KEY (`idPointCpt`)
    REFERENCES `POINT_CPT` (`idPointCpt`),
  CONSTRAINT `fkPointCptEleveNiveauCpt`
    FOREIGN KEY (`idNiveauCpt`)
    REFERENCES `NIVEAU_CPT` (`idNiveauCpt`))
ENGINE = InnoDB;

CREATE INDEX `fkPointCptEleveEleve_idx` ON `POINT_CPT_ELEVE` (`idEleve` ASC);

CREATE INDEX `fkPointCptEleveNiveauCpt_idx` ON `POINT_CPT_ELEVE` (`idNiveauCpt` ASC);


-- -----------------------------------------------------
-- Table `TYPE_EVALUATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TYPE_EVALUATION` (
  `idTypeEvaluation` INT NOT NULL AUTO_INCREMENT,
  `libelleTypeEvaluation` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idTypeEvaluation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EVALUATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EVALUATION` (
  `idEvaluation` INT NOT NULL AUTO_INCREMENT,
  `idTypeEvaluation` INT NOT NULL,
  `idMatiereNiveau` INT NOT NULL,
  `dateEvaluation` DATE NOT NULL,
  `titreEvaluation` VARCHAR(255) NOT NULL,
  `autreEvaluation` VARCHAR(255) NULL,
  `maxEvaluation` INT NOT NULL DEFAULT 20,
  PRIMARY KEY (`idEvaluation`),
  CONSTRAINT `fkEvaluationTypeEvaluation`
    FOREIGN KEY (`idTypeEvaluation`)
    REFERENCES `TYPE_EVALUATION` (`idTypeEvaluation`),
  CONSTRAINT `fkEvaluationMatiereNiveau`
    FOREIGN KEY (`idMatiereNiveau`)
    REFERENCES `MATIERE_NIVEAU` (`idMatiereNiveau`))
ENGINE = InnoDB;

CREATE INDEX `fkEvaluationTypeEvaluation_idx` ON `EVALUATION` (`idTypeEvaluation` ASC);

CREATE INDEX `fkEvaluationMatiereNiveau_idx` ON `EVALUATION` (`idMatiereNiveau` ASC);


-- -----------------------------------------------------
-- Table `EVALUATION_POINT_CPT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EVALUATION_POINT_CPT` (
  `idEvaluationPointCpt` INT NOT NULL AUTO_INCREMENT,
  `idEvaluation` INT NOT NULL,
  `idPointCpt` INT NOT NULL,
  PRIMARY KEY (`idEvaluationPointCpt`),
  CONSTRAINT `fkEvaluationPointCptEvaluation`
    FOREIGN KEY (`idEvaluation`)
    REFERENCES `EVALUATION` (`idEvaluation`),
  CONSTRAINT `fkEvaluationPointCptPointCpt`
    FOREIGN KEY (`idPointCpt`)
    REFERENCES `POINT_CPT` (`idPointCpt`))
ENGINE = InnoDB;

CREATE INDEX `fkEvaluationPointCptPointCpt_idx` ON `EVALUATION_POINT_CPT` (`idPointCpt` ASC);


-- -----------------------------------------------------
-- Table `CAHIER_TEXTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CAHIER_TEXTE` (
  `idCahierTexte` INT NOT NULL AUTO_INCREMENT,
  `idNiveau` INT NOT NULL,
  `dateRealisation` DATE NOT NULL,
  `contenuCahierTexte` TEXT NOT NULL,
  `idRedacteur` INT NOT NULL,
  `dateRedaction` DATETIME NOT NULL,
  PRIMARY KEY (`idCahierTexte`),
  CONSTRAINT `fkCahierTexteUtilisateur`
    FOREIGN KEY (`idRedacteur`)
    REFERENCES `UTILISATEUR` (`idUtilisateur`),
  CONSTRAINT `fkCahierTexteNiveau`
    FOREIGN KEY (`idNiveau`)
    REFERENCES `NIVEAU` (`idNiveau`))
ENGINE = InnoDB;

CREATE INDEX `fkCahierTexteUtilisateur_idx` ON `CAHIER_TEXTE` (`idRedacteur` ASC);

CREATE INDEX `fkCahierTexteNiveau_idx` ON `CAHIER_TEXTE` (`idNiveau` ASC);


-- -----------------------------------------------------
-- Table `CARNET_LIAISON`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CARNET_LIAISON` (
  `idCarnetLiaison` INT NOT NULL AUTO_INCREMENT,
  `contenuCarnetLiaison` TEXT NOT NULL,
  `idReponse` INT NULL,
  `idRedacteur` INT NOT NULL,
  `dateRedaction` DATETIME NOT NULL,
  `idEleve` INT NOT NULL,
  PRIMARY KEY (`idCarnetLiaison`),
  CONSTRAINT `fkCarnetLiaisonUtilisateur`
    FOREIGN KEY (`idRedacteur`)
    REFERENCES `UTILISATEUR` (`idUtilisateur`),
  CONSTRAINT `fkCarnetLiaisonReponse`
    FOREIGN KEY (`idReponse`)
    REFERENCES `CARNET_LIAISON` (`idCarnetLiaison`),
  CONSTRAINT `fkCarnetLiaisonEleve`
    FOREIGN KEY (`idEleve`)
    REFERENCES `ELEVE` (`idEleve`))
ENGINE = InnoDB;

CREATE INDEX `fkCarnetLiaisonUtilisateur_idx` ON `CARNET_LIAISON` (`idRedacteur` ASC);

CREATE INDEX `fkCarnetLiaisonReponse_idx` ON `CARNET_LIAISON` (`idReponse` ASC);

CREATE INDEX `fkCarnetLiaisonEleve_idx` ON `CARNET_LIAISON` (`idEleve` ASC);


-- -----------------------------------------------------
-- Table `COMMUNICATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COMMUNICATION` (
  `idCommunication` INT NOT NULL AUTO_INCREMENT,
  `contenuCommunication` TEXT NOT NULL,
  `idRedacteur` INT NOT NULL,
  `dateRedaction` DATETIME NOT NULL,
  PRIMARY KEY (`idCommunication`),
  CONSTRAINT `fkCommunicationUtilisateur`
    FOREIGN KEY (`idRedacteur`)
    REFERENCES `UTILISATEUR` (`idUtilisateur`))
ENGINE = InnoDB;

CREATE INDEX `fkCommunicationUtilisateur_idx` ON `COMMUNICATION` (`idRedacteur` ASC);


-- -----------------------------------------------------
-- Table `TRIMESTRE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TRIMESTRE` (
  `idTrismestre` INT NOT NULL AUTO_INCREMENT,
  `libelleTrimestre` VARCHAR(255) NOT NULL,
  `dateDebutTrimestre` DATE NOT NULL,
  `dateFinTimestre` DATE NOT NULL,
  `dateFinCommentaires` DATE NOT NULL,
  PRIMARY KEY (`idTrismestre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PERIODE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PERIODE` (
  `idPeriode` INT NOT NULL AUTO_INCREMENT,
  `libellePeriode` VARCHAR(255) NOT NULL,
  `dateDebutPeriode` DATE NOT NULL,
  `dateFinPeriode` DATE NOT NULL,
  `idTrimestre` INT NOT NULL,
  PRIMARY KEY (`idPeriode`),
  CONSTRAINT `fkPeriodeTrimestre`
    FOREIGN KEY (`idTrimestre`)
    REFERENCES `TRIMESTRE` (`idTrismestre`))
ENGINE = InnoDB;

CREATE INDEX `fkPeriodeTrimestre_idx` ON `PERIODE` (`idTrimestre` ASC);


-- -----------------------------------------------------
-- Table `PLAN_TRAVAIL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PLAN_TRAVAIL` (
  `idPlanTravail` INT NOT NULL,
  `libellePlanTravail` VARCHAR(255) NOT NULL,
  `idMatiereNiveau` INT NOT NULL,
  `idPeriode` INT NOT NULL,
  PRIMARY KEY (`idPlanTravail`),
  CONSTRAINT `fkPlanTravailPeriode`
    FOREIGN KEY (`idPeriode`)
    REFERENCES `PERIODE` (`idPeriode`),
  CONSTRAINT `fkPlanTravailMatiereNiveau`
    FOREIGN KEY (`idMatiereNiveau`)
    REFERENCES `MATIERE_NIVEAU` (`idMatiereNiveau`))
ENGINE = InnoDB;

CREATE INDEX `fkPlanTravailPeriode_idx` ON `PLAN_TRAVAIL` (`idPeriode` ASC);

CREATE INDEX `fkPlanTravailMatiereNiveau_idx` ON `PLAN_TRAVAIL` (`idMatiereNiveau` ASC);


-- -----------------------------------------------------
-- Table `ABSENCE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ABSENCE` (
  `idAbsence` INT NOT NULL AUTO_INCREMENT,
  `idEleve` INT NOT NULL,
  `dateDebutAbsence` DATETIME NOT NULL,
  `dateFinAbsence` DATETIME NOT NULL,
  `etatAbsence` TINYINT(1) NULL,
  `motifAbsence` TEXT NOT NULL,
  `dateRedaction` DATETIME NOT NULL,
  `idRedacteur` INT NOT NULL,
  PRIMARY KEY (`idAbsence`),
  CONSTRAINT `fkAbsenceEleve`
    FOREIGN KEY (`idEleve`)
    REFERENCES `ELEVE` (`idEleve`),
  CONSTRAINT `fkAbsenceRedecteur`
    FOREIGN KEY (`idRedacteur`)
    REFERENCES `UTILISATEUR` (`idUtilisateur`))
ENGINE = InnoDB;

CREATE INDEX `kfAbsenceEleve_idx` ON `ABSENCE` (`idEleve` ASC);

CREATE INDEX `fkAbsenceRedecteur_idx` ON `ABSENCE` (`idRedacteur` ASC);


-- -----------------------------------------------------
-- Table `NOTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NOTE` (
  `idEleve` INT NOT NULL,
  `idEvaluation` INT NOT NULL,
  `note` DECIMAL(4,2) NOT NULL,
  PRIMARY KEY (`idEleve`, `idEvaluation`),
  CONSTRAINT `fkNoteEleve`
    FOREIGN KEY (`idEleve`)
    REFERENCES `ELEVE` (`idEleve`),
  CONSTRAINT `fkNoteEvluation`
    FOREIGN KEY (`idEvaluation`)
    REFERENCES `EVALUATION` (`idEvaluation`))
ENGINE = InnoDB;

CREATE INDEX `fkNoteEvluation_idx` ON `NOTE` (`idEvaluation` ASC);


-- -----------------------------------------------------
-- Table `ELEVE_EVALUATION_POINT_CPT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ELEVE_EVALUATION_POINT_CPT` (
  `idEleve` INT NOT NULL,
  `idEvaluationPointCpt` INT NOT NULL,
  `idNiveauCpt` INT NOT NULL,
  PRIMARY KEY (`idEleve`, `idEvaluationPointCpt`),
  CONSTRAINT `fkEleveEvaluationPointCptEleve`
    FOREIGN KEY (`idEleve`)
    REFERENCES `ELEVE` (`idEleve`),
  CONSTRAINT `fkEleveEvaluationPointCptEvaluationPointCpt`
    FOREIGN KEY (`idEvaluationPointCpt`)
    REFERENCES `EVALUATION_POINT_CPT` (`idEvaluationPointCpt`),
  CONSTRAINT `fkEleveEvaluationPointCptNiveauCpt`
    FOREIGN KEY (`idNiveauCpt`)
    REFERENCES `NIVEAU_CPT` (`idNiveauCpt`))
ENGINE = InnoDB;

CREATE INDEX `fkEleveEvaluationPointCptEvaluationPointCpt_idx` ON `ELEVE_EVALUATION_POINT_CPT` (`idEvaluationPointCpt` ASC);

CREATE INDEX `fkEleveEvaluationPointCptNiveauCpt_idx` ON `ELEVE_EVALUATION_POINT_CPT` (`idNiveauCpt` ASC);


-- -----------------------------------------------------
-- Table `BULLETIN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BULLETIN` (
  `idBulletin` INT NOT NULL AUTO_INCREMENT,
  `dateRedaction` DATE NOT NULL,
  `contenuBulletin` TEXT NOT NULL,
  `idEleve` INT NOT NULL,
  `idMatiereNiveau` INT NOT NULL,
  PRIMARY KEY (`idBulletin`),
  CONSTRAINT `fkBulletinEleve`
    FOREIGN KEY (`idEleve`)
    REFERENCES `ELEVE` (`idEleve`),
  CONSTRAINT `fkBulletinMatiereNiveau`
    FOREIGN KEY (`idMatiereNiveau`)
    REFERENCES `MATIERE_NIVEAU` (`idMatiereNiveau`))
ENGINE = InnoDB;

CREATE INDEX `fkBulletinEleve_idx` ON `BULLETIN` (`idEleve` ASC);

CREATE INDEX `fkBulletinMatiereNiveau_idx` ON `BULLETIN` (`idMatiereNiveau` ASC);


-- -----------------------------------------------------
-- Table `EMPLOI_TEMPS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EMPLOI_TEMPS` (
  `idEdT` INT NOT NULL AUTO_INCREMENT,
  `idPeriode` INT NOT NULL,
  `idMatiereNiveau` INT NOT NULL,
  `jourEdT` VARCHAR(10) NOT NULL,
  `heureDebEdT` VARCHAR(5) NOT NULL,
  `heureFinEdT` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`idEdT`),
  CONSTRAINT `fkEdTPeriode`
    FOREIGN KEY (`idPeriode`)
    REFERENCES `PERIODE` (`idPeriode`),
  CONSTRAINT `fkEdtMatiereNiveau`
    FOREIGN KEY (`idMatiereNiveau`)
    REFERENCES `MATIERE_NIVEAU` (`idMatiereNiveau`))
ENGINE = InnoDB;

CREATE INDEX `fkEdTPeriode_idx` ON `EMPLOI_TEMPS` (`idPeriode` ASC);

CREATE INDEX `fkEdtMatiereNiveau_idx` ON `EMPLOI_TEMPS` (`idMatiereNiveau` ASC);


-- -----------------------------------------------------
-- Table `PROFESSEUR_MATIERE_NIVEAU`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROFESSEUR_MATIERE_NIVEAU` (
  `idProfesseurMatiereNiveau` INT NOT NULL AUTO_INCREMENT,
  `idProfesseur` INT NOT NULL,
  `idMatiereNiveau` INT NOT NULL,
  PRIMARY KEY (`idProfesseurMatiereNiveau`),
  CONSTRAINT `fkProfesseurMatiereNiveauProfesseur`
    FOREIGN KEY (`idProfesseur`)
    REFERENCES `PROFESSEUR` (`idProfesseur`),
  CONSTRAINT `fkProfesseurMatiereNiveauMatiereNiveau`
    FOREIGN KEY (`idMatiereNiveau`)
    REFERENCES `MATIERE_NIVEAU` (`idMatiereNiveau`))
ENGINE = InnoDB;

CREATE INDEX `fkProfesseurMatiereNiveauProfesseur_idx` ON `PROFESSEUR_MATIERE_NIVEAU` (`idProfesseur` ASC);

CREATE INDEX `fkProfesseurMatiereNiveauMatiereNiveau_idx` ON `PROFESSEUR_MATIERE_NIVEAU` (`idMatiereNiveau` ASC);


DELIMITER $$
CREATE TRIGGER `UTILISATEUR_AFTER_INSERT` 
AFTER INSERT 
ON `UTILISATEUR` 
FOR EACH ROW
begin
	INSERT INTO CONNEXION VALUES (NEW.idUtilisateur, CONCAT(NEW.nomUtilisateur, '.', NEW.prenomUtilisateur), 'bccc3f25b4b70a9e4704cab21dc772e932ff62af32aa475f15c4903044dec995');
end;$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
